import type { User, Professional, Category, Service, ScoredProfessional } from '../types';

export const DEMO_USERS: User[] = [
  {
    _id: 'user_admin_1',
    name: 'Alex Rivera (Admin)',
    email: 'admin@localpro.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    phone: '+1 (555) 019-2834',
    isVerified: true,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    _id: 'user_pro_1',
    name: 'David Vance',
    email: 'pro@localpro.com',
    role: 'professional',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    phone: '+1 (555) 438-9201',
    isVerified: true,
    isActive: true,
    createdAt: '2026-01-05T00:00:00.000Z',
  },
  {
    _id: 'user_pro_2',
    name: 'Sarah Jenkins',
    email: 'sarah@localpro.com',
    role: 'professional',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    phone: '+1 (555) 721-3948',
    isVerified: true,
    isActive: true,
    createdAt: '2026-01-07T00:00:00.000Z',
  },
  {
    _id: 'user_pro_3',
    name: 'Mike O\'Connor',
    email: 'mike@localpro.com',
    role: 'professional',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
    phone: '+1 (555) 912-4433',
    isVerified: true,
    isActive: true,
    createdAt: '2026-01-08T00:00:00.000Z',
  },
  {
    _id: 'user_customer_1',
    name: 'Sarah Connor',
    email: 'customer@localpro.com',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250',
    phone: '+1 (555) 839-1120',
    isVerified: true,
    isActive: true,
    createdAt: '2026-01-10T00:00:00.000Z',
  },
];

export const DEMO_CATEGORIES: Category[] = [
  {
    _id: 'cat_elec',
    name: 'Electrical & Wiring',
    slug: 'electrical',
    icon: 'Zap',
    description: 'Certified electricians for repairs, circuit breakers, rewiring and fixture setups.',
    isActive: true,
  },
  {
    _id: 'cat_plumb',
    name: 'Plumbing & Pipes',
    slug: 'plumbing',
    icon: 'Wrench',
    description: 'Leak detection, pipe repairs, faucet fixtures, drain cleaning and water heaters.',
    isActive: true,
  },
  {
    _id: 'cat_clean',
    name: 'Home Cleaning',
    slug: 'cleaning',
    icon: 'Sparkles',
    description: 'Deep residential cleaning, move-out sanitization, carpet cleaning, and recurring housekeeping.',
    isActive: true,
  },
  {
    _id: 'cat_carp',
    name: 'Carpentry & Handyman',
    slug: 'carpentry',
    icon: 'Hammer',
    description: 'Custom cabinetry, furniture assembly, doors, drywall repairs and structural woodwork.',
    isActive: true,
  },
  {
    _id: 'cat_paint',
    name: 'Painting & Decor',
    slug: 'painting',
    icon: 'Paintbrush',
    description: 'Interior and exterior wall painting, priming, wallpaper removal, and decorative finishes.',
    isActive: true,
  },
  {
    _id: 'cat_app',
    name: 'Appliance Repair',
    slug: 'appliances',
    icon: 'Cpu',
    description: 'Diagnostic troubleshooting and repair for refrigerators, washers, dryers, and HVAC systems.',
    isActive: true,
  },
];

export const DEMO_PROFESSIONALS: Professional[] = [
  {
    _id: 'pro_1',
    userId: DEMO_USERS[1],
    category: DEMO_CATEGORIES[0],
    title: 'Master Licensed Electrician',
    bio: 'Over 12 years of residential & commercial wiring experience. Certified in smart home automation, EV charger installations, and comprehensive breaker panel upgrades.',
    hourlyRate: 85,
    experienceYears: 12,
    location: { city: 'New York', state: 'NY', country: 'USA' },
    isApproved: true,
    rating: 4.9,
    reviewCount: 48,
    portfolio: [
      { title: 'Sub-panel Replacement', imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=600' },
      { title: 'Recessed Lighting Setup', imageUrl: 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?auto=format&fit=crop&q=80&w=600' },
    ],
    createdAt: '2026-01-05T00:00:00.000Z',
  },
  {
    _id: 'pro_2',
    userId: DEMO_USERS[2],
    category: DEMO_CATEGORIES[0],
    title: 'High-Voltage Specialist & Smart Systems',
    bio: 'Specializing in residential energy efficiency, solar inverter troubleshooting, smart thermostat networks, and emergency outage restoration.',
    hourlyRate: 95,
    experienceYears: 9,
    location: { city: 'Brooklyn', state: 'NY', country: 'USA' },
    isApproved: true,
    rating: 4.8,
    reviewCount: 32,
    portfolio: [
      { title: 'Smart Switch Installation', imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=600' },
    ],
    createdAt: '2026-01-07T00:00:00.000Z',
  },
  {
    _id: 'pro_3',
    userId: DEMO_USERS[3],
    category: DEMO_CATEGORIES[1],
    title: 'Certified Plumbing Contractor',
    bio: '24/7 emergency response plumbing. Trenchless sewer inspections, water softener systems, whole-home copper repiping, and tankless heater conversions.',
    hourlyRate: 75,
    experienceYears: 15,
    location: { city: 'Queens', state: 'NY', country: 'USA' },
    isApproved: true,
    rating: 4.95,
    reviewCount: 64,
    portfolio: [
      { title: 'Tankless Water Heater', imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600' },
    ],
    createdAt: '2026-01-08T00:00:00.000Z',
  },
];

export const DEMO_SERVICES: Service[] = [
  {
    _id: 'serv_1',
    professionalId: 'pro_1',
    category: 'cat_elec',
    title: 'Comprehensive Electrical Diagnostic & Inspection',
    description: 'Full examination of breaker panels, outlet grounding, AFCI/GFCI readiness, and load calculation.',
    price: 120,
    durationMinutes: 60,
    isActive: true,
    createdAt: '2026-01-05T00:00:00.000Z',
  },
  {
    _id: 'serv_2',
    professionalId: 'pro_1',
    category: 'cat_elec',
    title: 'EV Level-2 Charger Installation',
    description: 'Dedicated 240V 50A breaker circuit wiring and wall mount charging box setup with code compliance test.',
    price: 350,
    durationMinutes: 180,
    isActive: true,
    createdAt: '2026-01-05T00:00:00.000Z',
  },
  {
    _id: 'serv_3',
    professionalId: 'pro_3',
    category: 'cat_plumb',
    title: 'Drain Snaking & Hydro-Jet Clearing',
    description: 'High-pressure water jetting and motorized snake equipment to dissolve tough clogs and roots.',
    price: 160,
    durationMinutes: 90,
    isActive: true,
    createdAt: '2026-01-08T00:00:00.000Z',
  },
];

export const DEMO_RECOMMENDATIONS: ScoredProfessional[] = [
  {
    professional: DEMO_PROFESSIONALS[0],
    score: 98,
    matchFactors: {
      ratingScore: 98,
      experienceScore: 95,
      popularityScore: 94,
      completionScore: 100,
      valueScore: 90,
    },
    recommendationReason: 'Elite 4.9★ satisfaction, 12+ years master trade experience & verified arrival track record.',
  },
  {
    professional: DEMO_PROFESSIONALS[2],
    score: 95,
    matchFactors: {
      ratingScore: 99,
      experienceScore: 100,
      popularityScore: 92,
      completionScore: 96,
      valueScore: 88,
    },
    recommendationReason: 'Top-Rated Plumber in NYC with 60+ verified reviews and fair transparent rates.',
  },
  {
    professional: DEMO_PROFESSIONALS[1],
    score: 92,
    matchFactors: {
      ratingScore: 96,
      experienceScore: 90,
      popularityScore: 88,
      completionScore: 92,
      valueScore: 94,
    },
    recommendationReason: 'Smart Home Specialist with rapid 1-hour average response time.',
  },
];

